---
# tasks file for ansible-role-set-cloud9
- import_tasks: "install-inspec.yml"
- import_tasks: "install-git-secrets.yml"
- import_tasks: "install-docker-compose.yml"
- import_tasks: "install-ecs-cli.yml"
- import_tasks: "install-awslogs.yml"
- import_tasks: "install-molecule.yml"
- import_tasks: "install-packages.yml"
- import_tasks: "install-pulumi.yml"
